export const ProcurementResponse = {
    "total": 23161,
    "data": [{
        "id": 89730,
        "proekt": "Test upload",
        "pid": "ПИД1",
        "data_vneseniya_potrebnosti": "15.09.21",
        "nomer_zayavki": "Заявка №00000694987 от 17:04:40",
        "titul_rd": "Титул 10",
        "shifr_rd": "Марка 1",
        "shifr_proekta": "Vsdasdas",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "1.0",
        "naimenovanie_mtr_po_rd": "Абразивный материал ",
        "marka_tip_gost_ol_mtr": "ГОСТ 9.402",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 3926.080000,
        "ed_izm_fakticheskaya": "кг",
        "koeff_perescheta_v_fakticheskie_ed_izm": 1.000000,
        "kolvo_vsego_fakticheskoe": 3926.080000000000,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 21.000000,
        "kolvo_vsego_bazovoe": 82447.680000000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 2",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "20.04.22",
        "kommentarij_komplektaciya": "Для закупки",
        "ed_izm_po_ens": "кг",
        "koeff_perescheta_v_ed_izm_po_ens": 21.000000,
        "kolvo_vsego_po_ens": 82447.680000000000,
        "otvetstvennyj_za_postavku_so_storony_genpodryadchika": "Аня Панова",
        "tekushchij_status_prorabotki_mtr": "Поставка",
        "postavshchik": "TEST LLC",
        "orientirovochnaya_data_postavki": "01.02.23",
        "otklonenie_postavki": -315,
        "nomer_i_data_dogovora_s_postavshchikom": "1",
        "nomer_i_data_specifikacii_s_postavshchikom": "1",
        "bazis_postavki": "1",
        "naimenovanie_mtr_fakticheskoe": "Материал",
        "kolvo_zakontraktovano_rd": 5033.000000,
        "kolvo_kontraktacii_fakticheskoe": 5033.000000,
        "kolvo_kontraktacii_bazovoe": 105693.000000000000,
        "kolvo_kontraktacii_ens": 105693.000000000000,
        "cena_kontraktacii_fakticheskaya_rub_bez_nds": 150.00,
        "orientirovochnaya_stoimost_kontraktacii_rub_bez_NDS": 441076.00,
        "srednyaya_cena_kontraktacii_rub_bez_NDS": 87.63679714,
        "orientirovochnaya_cena_rd_rub_bez_nds": 100.00,
        "orientirovochnaya_stoimost_rd_rub_bez_nds": 441076.00,
        "procent_kontraktacii_rd_kolvo": 128.19,
        "procent_kontraktacii_rd_stoimost": 100.00,
        "kommentarij_zakupka": "К10+10/О5+5",
        "kolvo_otgruzheno_rd": 4620.000000,
        "kolvo_otgruzheno_fakticheskoe": 4620.000000,
        "kolvo_otgruzheno_bazovoe": 97020.000000000000,
        "kolvo_otgruzheno_ens": 97020.000000000000,
        "stoimost_otgruzki_rd_rub_bez_nds": 404882.00,
        "procent_otgruzki_rd_kolvo": 117.67,
        "procent_otgruzki_rd_stoimost": 91.79,
        "data_otgruzki": "08.02.23",
        "nomer_schf": "1",
        "data_schf": "08.02.23",
        "nomer_ttn": "1",
        "data_ttn": "08.02.23",
        "perevozchik": "Тест",
        "kolvo_v_logistike": 320.000000,
        "stoimost_mtr": 28043.78,
        "stoimost_logistiki_za_partiyu": 100.00,
        "stoimost_logistiki": 100.00,
        "vid_dostavki": "Авиа",
        "massa_za_ed_tonn": 2.000000,
        "mesto_perevalki": "Тверь",
        "gabarity_za_ed_m3": 42.000000,
        "data_postupleniya_v_port_perevalki": "01.02.23",
        "kommentarij_logistika": "Тест 3",
        "data_postavki": "08.02.23",
        "kolvo_postavleno_rd": 1645.000000,
        "kolvo_postavlennoe_fakticheskoe": 1645.000000,
        "kolvo_postavleno_bazovoe": 34545.000000000000,
        "kolvo_postavleno_ens": 34545.000000000000,
        "stoimost_postavki_rd_rub_bez_nds": 144162.53,
        "procent_postavki_rd_kolvo": 41.90,
        "procent_postavki_rd_stoimost": 32.68,
        "data_oprihodovaniya": "25.02.23",
        "kolvo_oprihodovano_rd": 1386.000000,
        "kolvo_oprihodovannoe_fakticheskoe": 1386.000000,
        "kolvo_oprihodovano_bazovoe": 29106.000000000000,
        "kolvo_oprihodovannoe_ens": 29106.000000000000,
        "nomer_akta_vhodnogo_kontrolya": "1",
        "stoimost_oprihodovano_rd_rub_bez_nds": 121464.60,
        "data_akta_vhodnogo_kontrolya": "08.02.23",
        "procent_oprihodovano_rd_kolvo": 35.30,
        "procent_oprihodovano_rd_stoimost": 27.54,
        "kolvo_vydano_rd": 295.000000,
        "kolvo_vydannoe_fakticheskoe": 295.000000,
        "kolvo_vydano_bazovoe": 6195.000000000000,
        "kolvo_vydano_ens": 6195.000000000000,
        "stoimost_vydano_rd_rub_bez_nds": 25852.86,
        "procent_vydano_rd_kolvo": 7.51,
        "procent_vydano_rd_stoimost": 5.86,
        "data_vydachi": "08.02.23",
        "proizvoditel_rabot": "1",
        "nomer_zayavki_na_vydachu": "1",
        "data_zayavki_na_vydachu": "08.02.23",
        "dostupno_k_otgruzke": 413.000000,
        "dostupno_k_postupleniyu": 2975.000000,
        "dostupno_k_oprihodovaniyu": 259.000000,
        "dostupno_k_vydache": 1091.000000
    }, {
        "id": 89731,
        "proekt": "Test upload",
        "pid": "ПИД2",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "фывфыв цукцуццукцу",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "йцуйцу",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "10, 11.12",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.355110,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 21.000000,
        "kolvo_vsego_bazovoe": 7.457310000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "ed_izm_po_ens": "кг",
        "koeff_perescheta_v_ed_izm_po_ens": 21.000000,
        "kolvo_vsego_po_ens": 7.457310000000,
        "tekushchij_status_prorabotki_mtr": "Поставка",
        "orientirovochnaya_data_postavki": "01.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89732,
        "proekt": "Test upload",
        "pid": "ПИД3",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": " цукцув йцуйцу",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "10, 11.12",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.116626,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 21.000000,
        "kolvo_vsego_bazovoe": 2.449146000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "ed_izm_po_ens": "кг",
        "koeff_perescheta_v_ed_izm_po_ens": 21.000000,
        "kolvo_vsego_po_ens": 2.449146000000,
        "orientirovochnaya_data_postavki": "01.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89733,
        "proekt": "Test upload",
        "pid": "ПИД4",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "ыыыыыыыыыыыыыыыыы йцуйцу",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "10, 11.12",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.017755,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.017755000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "orientirovochnaya_data_postavki": "08.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89734,
        "proekt": "Test upload",
        "pid": "ПИД5",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694947 от 17.12.2021 17:03:55",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "10, 11.12",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.047174,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.047174000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "orientirovochnaya_data_postavki": "08.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89735,
        "proekt": "Test upload",
        "pid": "ПИД6",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "мчсмчсм",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "13",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.216258,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.216258000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "orientirovochnaya_data_postavki": "01.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89736,
        "proekt": "Test upload",
        "pid": "ПИД7",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694914 от 17.12.2021 17:03: цукцук20",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "13",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.071024,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.071024000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "orientirovochnaya_data_postavki": "17.02.23",
        "otklonenie_postavki": -281
    }, {
        "id": 89737,
        "proekt": "Test upload",
        "pid": "ПИД8",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": " йцуйцуЗаявка №00000694950 от 17.12.2021 17:03:57",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "13",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.010813,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.010813000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89738,
        "proekt": "Test upload",
        "pid": "ПИД9",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "йцуйцу 17:03:59",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС2",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "13",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.028728,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.028728000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89739,
        "proekt": "Test upload",
        "pid": "ПИД10",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694915 от 17.12.2021 17:03:22",
        "titul_rd": "Титул 1",
        "shifr_rd": "КЖ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КЖ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "5",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.437570,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.437570000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89740,
        "proekt": "Test upload",
        "pid": "ПИД11",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694916 от 17.12.2021 17:03:23",
        "titul_rd": "Титул 1",
        "shifr_rd": "КЖ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КЖ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "5",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.143707,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.143707000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89741,
        "proekt": "Test upload",
        "pid": "ПИД12",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694919 от 17.12.2021 17:04:01",
        "titul_rd": "Титул 1",
        "shifr_rd": "КЖ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КЖ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "5",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.021879,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.021879000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89742,
        "proekt": "Test upload",
        "pid": "ПИД13",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694929 от 17.12.2021 17:04:02",
        "titul_rd": "Титул 1",
        "shifr_rd": "КЖ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КЖ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "5",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.058128,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.058128000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89743,
        "proekt": "Test upload",
        "pid": "ПИД14",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694921 от 17.12.2021 17:03:27",
        "titul_rd": "Титул 1",
        "shifr_rd": "КМ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КМ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "2, -.-КМ1.СМ",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 49.646905,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 49.646905000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89744,
        "proekt": "Test upload",
        "pid": "ПИД15",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "цукцук3:28",
        "titul_rd": "Титул 1",
        "shifr_rd": "КМ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КМ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "2, -.-КМ1.СМ",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 32.610178,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 32.610178000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89745,
        "proekt": "Test upload",
        "pid": "ПИД16",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "укцукцукЗаявка №00000694958 от 17.12.2021 17:04:09 цукцук",
        "titul_rd": "Титул 1",
        "shifr_rd": "КМ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КМ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "2, -.-КМ1.СМ",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 2.482345,
        "ed_izm_fakticheskaya": "к-кт",
        "koeff_perescheta_v_fakticheskie_ed_izm": 1.000000,
        "kolvo_vsego_fakticheskoe": 2.482345000000,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 2.482345000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки",
        "tekushchij_status_prorabotki_mtr": "Контрактация",
        "postavshchik": "АО ТЕСТ",
        "nomer_i_data_dogovora_s_postavshchikom": "2",
        "nomer_i_data_specifikacii_s_postavshchikom": "2",
        "bazis_postavki": "2",
        "naimenovanie_mtr_fakticheskoe": "ывываыа",
        "kolvo_zakontraktovano_rd": 6036036017.000000,
        "kolvo_kontraktacii_fakticheskoe": 6036036017.000000,
        "kolvo_kontraktacii_bazovoe": 6036036017.000000000000,
        "cena_kontraktacii_fakticheskaya_rub_bez_nds": 2342342342.00,
        "orientirovochnaya_stoimost_kontraktacii_rub_bez_NDS": 10034358635190866536.52,
        "srednyaya_cena_kontraktacii_rub_bez_NDS": 1662408674.65500853,
        "orientirovochnaya_cena_rd_rub_bez_nds": 1231231231.00,
        "orientirovochnaya_stoimost_rd_rub_bez_nds": 10034358635190866536.52,
        "procent_kontraktacii_rd_kolvo": 243158626903.19,
        "procent_kontraktacii_rd_stoimost": 100.00,
        "dostupno_k_otgruzke": 6036036017.000000
    }, {
        "id": 89746,
        "proekt": "Test upload",
        "pid": "ПИД17",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694959 от 17.12.2021 17:04:10",
        "titul_rd": "Титул 1",
        "shifr_rd": "КМ",
        "shifr_proekta": "Чертеж-Проект-Титул 1-КМ1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "2, -.-КМ1.СМ",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 8.225708,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 8.225708000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89747,
        "proekt": "Test upload",
        "pid": "ПИД18",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "цукцукцууЗаявка №00000694923 от 17.12.2021 17:03:29",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "1,2,5, -.-АС1.И-В1,К1, -.-АС1.И-Оп1...Оп3",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 5.648510,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 5.648510000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89748,
        "proekt": "Test upload",
        "pid": "ПИД19",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694924 от 17.12.2021 17:03:31",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "1,2,5, -.-АС1.И-В1,К1, -.-АС1.И-Оп1...Оп3",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 1.855090,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 1.855090000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89749,
        "proekt": "Test upload",
        "pid": "ПИД20",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "цукцукцукцуЗаявка №00000694961 от 17.12.2021 17:04:14",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "1,2,5, -.-АС1.И-В1,К1, -.-АС1.И-Оп1...Оп3",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.282425,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.282425000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89750,
        "proekt": "Test upload",
        "pid": "ПИД21",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694962 от 17.12.2021 17:04:15",
        "titul_rd": "Титул 1",
        "shifr_rd": "АС",
        "shifr_proekta": "Чертеж-Проект-Титул 1-АС1",
        "redakciya_specifikacii": "Ред.0",
        "list_specifikacii": "1,2,5, -.-АС1.И-В1,К1, -.-АС1.И-Оп1...Оп3",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 0.750360,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 0.750360000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89751,
        "proekt": "Test upload",
        "pid": "ПИД22",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694926 от 17.12.2021 17:03:33",
        "titul_rd": "Титул 11",
        "shifr_rd": "ЭС1",
        "shifr_proekta": "Чертеж-Проект-Титул 11-ЭС1.АН",
        "redakciya_specifikacii": "АН",
        "list_specifikacii": "ЭС1.С2.АН Лист2",
        "naimenovanie_mtr_po_rd": "ЦИНОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 14.830830,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 14.830830000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89752,
        "proekt": "Test upload",
        "pid": "ПИД23",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694927 от 17.12.2021 17:03:35",
        "titul_rd": "Титул 11",
        "shifr_rd": "ЭС1",
        "shifr_proekta": "Чертеж-Проект-Титул 11-ЭС1.АН",
        "redakciya_specifikacii": "АН",
        "list_specifikacii": "ЭС1.С2.АН Лист2",
        "naimenovanie_mtr_po_rd": "АЛПОЛ",
        "marka_tip_gost_ol_mtr": "ТУ 2313-012-12288779-99",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 9.741514,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 9.741514000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89753,
        "proekt": "Test upload",
        "pid": "ПИД24",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694965 от 17.12.2021 17:04:17",
        "titul_rd": "Титул 11",
        "shifr_rd": "ЭС1",
        "shifr_proekta": "Чертеж-Проект-Титул 11-ЭС1.АН",
        "redakciya_specifikacii": "АН",
        "list_specifikacii": "ЭС1.С2.АН Лист2",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 2.224625,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 2.224625000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }, {
        "id": 89754,
        "proekt": "Test upload",
        "pid": "ПИД25",
        "data_vneseniya_potrebnosti": "26.01.22",
        "nomer_zayavki": "Заявка №00000694967 от 17.12.2021 17:04:18",
        "titul_rd": "Титул 11",
        "shifr_rd": "ЭС1",
        "shifr_proekta": "Чертеж-Проект-Титул 11-ЭС1.АН",
        "redakciya_specifikacii": "АН",
        "list_specifikacii": "ЭС1.С2.АН Лист2",
        "naimenovanie_mtr_po_rd": "СОЛЬВ-УР",
        "marka_tip_gost_ol_mtr": "ТУ 2319-032-12288779-2002",
        "ed_izm_po_rd": "кг",
        "kolvo_vsego_po_rd": 1.461227,
        "ed_izm_bazovaya": "",
        "koeff_perescheta_v_bazovye_ed_izm": 1.000000,
        "kolvo_vsego_bazovoe": 1.461227000000,
        "gruppa_mtr": "Прочее",
        "gruppa_mtr_companii": "Антикор",
        "otvetstvennoe_podrazdelenie_za_postavku": "Подразделение 4",
        "model_postavki": "Модель поставки III",
        "razdelenie_postavki": "Подрядчик",
        "direktivnaya_data_postavki": "24.05.22",
        "kommentarij_komplektaciya": "Для закупки"
    }],
    "fields": ["id", 
    "proekt", 
    "genpodryadchik", 
    "pid", 
    "data_vneseniya_potrebnosti", 
    "nomer_zayavki", 
    "titul_rd", 
    "shifr_rd", 
    "shifr_proekta", 
    "redakciya_specifikacii", 
    "list_specifikacii", 
    "poziciya_na_specifikacii", 
    "naimenovanie_mtr_po_rd", 
    "marka_tip_gost_ol_mtr", 
    "dop_trebovaniya_mtr", 
    "ed_izm_po_rd", 
    "kolvo_vsego_po_rd", 
    "ed_izm_fakticheskaya", 
    "koeff_perescheta_v_fakticheskie_ed_izm", 
    "kolvo_vsego_fakticheskoe", 
    "ed_izm_bazovaya", 
    "koeff_perescheta_v_bazovye_ed_izm", 
    "kolvo_vsego_bazovoe", 
    "smr", 
    "gruppa_mtr", 
    "gruppa_mtr_companii", 
    "otvetstvennoe_podrazdelenie_za_postavku",
     "model_postavki",
     "razdelenie_postavki",
     "direktivnaya_data_postavki",
     "planiruemaya_data_montaja",
     "kommentarij_komplektaciya",
     "zapros_ens",
     "gid_ens",
     "razdelitelnaya_vedomost",
     "nomer_prejskuranta",
     "data_prejskuranta",
     "nomer_ish_pisma_na_zakazchika_na_soglasovanie_AC",
     "data_napravleniya_pisma_na_soglasovanie_AC",
     "nomer_vh_pisma_po_soglasovaniyu_AC",
     "data_polucheniya_pisma_na_soglasovanie_AC",
     "naimenovanie_mtr_po_ens",
     "gost_tu_po_ens",
     "marka_tip_mtr_po_ens",
     "chertyoj_ol_it_po_ens",
     "tehnicheskaya_harakteristika_po_ens",
     "ed_izm_po_ens",
     "koeff_perescheta_v_ed_izm_po_ens",
     "kolvo_vsego_po_ens",
     "otvetstvennyj_za_postavku_so_storony_genpodryadchika",
     "tekushchij_status_prorabotki_mtr",
      "status_postavki",
      "izgotovitel",
      "postavshchik",
      "orientirovochnaya_data_postavki",
      "otklonenie_postavki",
      "nomer_i_data_dogovora_s_postavshchikom",
      "nomer_i_data_specifikacii_s_postavshchikom",
      "bazis_postavki",
      "data_vybora_postavshchika_odci",
      "data_razrabotki_kdno",
      "data_soglasovaniya_kdno",
      "naimenovanie_mtr_fakticheskoe",
      "kolvo_zakontraktovano_rd",
      "kolvo_kontraktacii_fakticheskoe",
      "kolvo_kontraktacii_bazovoe",
      "kolvo_kontraktacii_ens",
      "cena_kontraktacii_fakticheskaya_rub_bez_nds",
      "orientirovochnaya_stoimost_kontraktacii_rub_bez_NDS",
      "srednyaya_cena_kontraktacii_rub_bez_NDS",
      "orientirovochnaya_cena_rd_rub_bez_nds",
      "orientirovochnaya_stoimost_rd_rub_bez_nds",
      "procent_kontraktacii_rd_kolvo",
      "procent_kontraktacii_rd_stoimost",
      "kommentarij_zakupka",
      "kolvo_otgruzheno_rd",
      "kolvo_otgruzheno_fakticheskoe",
      "kolvo_otgruzheno_bazovoe",
      "kolvo_otgruzheno_ens",
      "stoimost_otgruzki_rd_rub_bez_nds",
      "procent_otgruzki_rd_kolvo",
      "procent_otgruzki_rd_stoimost",
      "data_otgruzki",
      "nomer_schf",
      "data_schf",
      "nomer_ttn",
      "data_ttn",
      "perevozchik",
      "kolvo_v_logistike",
      "stoimost_mtr",
      "stoimost_logistiki_za_partiyu",
      "stoimost_logistiki",
      "vid_dostavki",
      "massa_za_ed_tonn",
      "mesto_perevalki",
      "gabarity_za_ed_m3",
      "data_postupleniya_v_port_perevalki",
      "kommentarij_logistika",
      "data_postavki",
      "kolvo_postavleno_rd",
      "kolvo_postavlennoe_fakticheskoe",
      "kolvo_postavleno_bazovoe",
      "kolvo_postavleno_ens",
      "stoimost_postavki_rd_rub_bez_nds",
      "procent_postavki_rd_kolvo",
      "procent_postavki_rd_stoimost",
      "data_oprihodovaniya",
      "kolvo_oprihodovano_rd",
      "kolvo_oprihodovannoe_fakticheskoe",
      "kolvo_oprihodovano_bazovoe",
      "kolvo_oprihodovannoe_ens",
      "nomer_akta_vhodnogo_kontrolya",
      "stoimost_oprihodovano_rd_rub_bez_nds",
      "data_akta_vhodnogo_kontrolya",
      "procent_oprihodovano_rd_kolvo",
      "procent_oprihodovano_rd_stoimost",
      "kolvo_vydano_rd",
      "kolvo_vydannoe_fakticheskoe",
      "kolvo_vydano_bazovoe",
      "kolvo_vydano_ens",
      "stoimost_vydano_rd_rub_bez_nds",
      "procent_vydano_rd_kolvo",
      "procent_vydano_rd_stoimost",
      "data_vydachi",
      "proizvoditel_rabot",
       "nomer_zayavki_na_vydachu",
       "data_zayavki_na_vydachu",
       "stoimost_kontractacii_documenta",
       "data_kontraktacii",
       "dostupno_k_otgruzke",
       "dostupno_k_postupleniyu",
       "dostupno_k_oprihodovaniyu",
       "dostupno_k_vydache"]
}